netbox/core/api/urls.py
from netbox.api.routers import NetBoxRouter
from . import views


router = NetBoxRouter()
router.APIRootView = views.CoreRootView

# Data sources
router.register('data-sources', views.DataSourceViewSet)
router.register('data-files', views.DataFileViewSet)

# Jobs
router.register('jobs', views.JobViewSet)

app_name = 'core-api'
urlpatterns = router.urls

netbox/core/urls.py
from django.urls import include, path

from utilities.urls import get_model_urls
from . import views

app_name = 'core'
urlpatterns = (

    # Data sources
    path('data-sources/', views.DataSourceListView.as_view(), name='datasource_list'),
    path('data-sources/add/', views.DataSourceEditView.as_view(), name='datasource_add'),
    path('data-sources/import/', views.DataSourceBulkImportView.as_view(), name='datasource_import'),
    path('data-sources/edit/', views.DataSourceBulkEditView.as_view(), name='datasource_bulk_edit'),
    path('data-sources/delete/', views.DataSourceBulkDeleteView.as_view(), name='datasource_bulk_delete'),
    path('data-sources/<int:pk>/', include(get_model_urls('core', 'datasource'))),

    # Data files
    path('data-files/', views.DataFileListView.as_view(), name='datafile_list'),
    path('data-files/delete/', views.DataFileBulkDeleteView.as_view(), name='datafile_bulk_delete'),
    path('data-files/<int:pk>/', include(get_model_urls('core', 'datafile'))),

    # Job results
    path('jobs/', views.JobListView.as_view(), name='job_list'),
    path('jobs/delete/', views.JobBulkDeleteView.as_view(), name='job_bulk_delete'),
    path('jobs/<int:pk>/', views.JobView.as_view(), name='job'),
    path('jobs/<int:pk>/delete/', views.JobDeleteView.as_view(), name='job_delete'),

    # Config revisions
    path('config-revisions/', views.ConfigRevisionListView.as_view(), name='configrevision_list'),
    path('config-revisions/add/', views.ConfigRevisionEditView.as_view(), name='configrevision_add'),
    path('config-revisions/delete/', views.ConfigRevisionBulkDeleteView.as_view(), name='configrevision_bulk_delete'),
    path('config-revisions/<int:pk>/restore/', views.ConfigRevisionRestoreView.as_view(), name='configrevision_restore'),
    path('config-revisions/<int:pk>/', include(get_model_urls('core', 'configrevision'))),

    # Configuration
    path('config/', views.ConfigView.as_view(), name='config'),

)

netbox/netbox/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from django.views.static import serve
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from account.views import LoginView, LogoutView
from netbox.api.views import APIRootView, StatusView
from netbox.graphql.schema import schema
from netbox.graphql.views import GraphQLView
from netbox.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
from netbox.views import HomeView, StaticMediaFailureView, SearchView, htmx
from .admin import admin_site

_patterns = [

    # Base views
    path('', HomeView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),

    # Login/logout
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('oauth/', include('social_django.urls', namespace='social')),

    # Apps
    path('circuits/', include('circuits.urls')),
    path('core/', include('core.urls')),
    path('dcim/', include('dcim.urls')),
    path('extras/', include('extras.urls')),
    path('ipam/', include('ipam.urls')),
    path('tenancy/', include('tenancy.urls')),
    path('users/', include('users.urls')),
    path('virtualization/', include('virtualization.urls')),
    path('vpn/', include('vpn.urls')),
    path('wireless/', include('wireless.urls')),

    # Current user views
    path('user/', include('account.urls')),

    # HTMX views
    path('htmx/object-selector/', htmx.ObjectSelectorView.as_view(), name='htmx_object_selector'),

    # API
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/circuits/', include('circuits.api.urls')),
    path('api/core/', include('core.api.urls')),
    path('api/dcim/', include('dcim.api.urls')),
    path('api/extras/', include('extras.api.urls')),
    path('api/ipam/', include('ipam.api.urls')),
    path('api/tenancy/', include('tenancy.api.urls')),
    path('api/users/', include('users.api.urls')),
    path('api/virtualization/', include('virtualization.api.urls')),
    path('api/vpn/', include('vpn.api.urls')),
    path('api/wireless/', include('wireless.api.urls')),
    path('api/status/', StatusView.as_view(), name='api-status'),

    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='api_docs'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='api_redocs'),

    # GraphQL
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema)), name='graphql'),

    # Serving static media in Django to pipe it through LoginRequiredMiddleware
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    path('media-failure/', StaticMediaFailureView.as_view(), name='media_failure'),

    # Plugins
    path('plugins/', include((plugin_patterns, 'plugins'))),
    path('api/plugins/', include((plugin_api_patterns, 'plugins-api'))),

    # Admin
    path('admin/background-tasks/', include('django_rq.urls')),
    path('admin/plugins/', include(plugin_admin_patterns)),
    path('admin/', admin_site.urls),
]


if settings.DEBUG:
    import debug_toolbar
    _patterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

if settings.METRICS_ENABLED:
    _patterns += [
        path('', include('django_prometheus.urls')),
    ]

# Prepend BASE_PATH
urlpatterns = [
    path('{}'.format(settings.BASE_PATH), include(_patterns))
]

handler404 = 'netbox.views.errors.handler_404'
handler500 = 'netbox.views.errors.handler_500'

netbox/vpn/urls.py
from django.urls import include, path

from utilities.urls import get_model_urls
from . import views

app_name = 'vpn'
urlpatterns = [

    # Tunnel groups
    path('tunnel-groups/', views.TunnelGroupListView.as_view(), name='tunnelgroup_list'),
    path('tunnel-groups/add/', views.TunnelGroupEditView.as_view(), name='tunnelgroup_add'),
    path('tunnel-groups/import/', views.TunnelGroupBulkImportView.as_view(), name='tunnelgroup_import'),
    path('tunnel-groups/edit/', views.TunnelGroupBulkEditView.as_view(), name='tunnelgroup_bulk_edit'),
    path('tunnel-groups/delete/', views.TunnelGroupBulkDeleteView.as_view(), name='tunnelgroup_bulk_delete'),
    path('tunnel-groups/<int:pk>/', include(get_model_urls('vpn', 'tunnelgroup'))),

    # Tunnels
    path('tunnels/', views.TunnelListView.as_view(), name='tunnel_list'),
    path('tunnels/add/', views.TunnelEditView.as_view(), name='tunnel_add'),
    path('tunnels/import/', views.TunnelBulkImportView.as_view(), name='tunnel_import'),
    path('tunnels/edit/', views.TunnelBulkEditView.as_view(), name='tunnel_bulk_edit'),
    path('tunnels/delete/', views.TunnelBulkDeleteView.as_view(), name='tunnel_bulk_delete'),
    path('tunnels/<int:pk>/', include(get_model_urls('vpn', 'tunnel'))),

    # Tunnel terminations
    path('tunnel-terminations/', views.TunnelTerminationListView.as_view(), name='tunneltermination_list'),
    path('tunnel-terminations/add/', views.TunnelTerminationEditView.as_view(), name='tunneltermination_add'),
    path('tunnel-terminations/import/', views.TunnelTerminationBulkImportView.as_view(), name='tunneltermination_import'),
    path('tunnel-terminations/edit/', views.TunnelTerminationBulkEditView.as_view(), name='tunneltermination_bulk_edit'),
    path('tunnel-terminations/delete/', views.TunnelTerminationBulkDeleteView.as_view(), name='tunneltermination_bulk_delete'),
    path('tunnel-terminations/<int:pk>/', include(get_model_urls('vpn', 'tunneltermination'))),

    # IKE proposals
    path('ike-proposals/', views.IKEProposalListView.as_view(), name='ikeproposal_list'),
    path('ike-proposals/add/', views.IKEProposalEditView.as_view(), name='ikeproposal_add'),
    path('ike-proposals/import/', views.IKEProposalBulkImportView.as_view(), name='ikeproposal_import'),
    path('ike-proposals/edit/', views.IKEProposalBulkEditView.as_view(), name='ikeproposal_bulk_edit'),
    path('ike-proposals/delete/', views.IKEProposalBulkDeleteView.as_view(), name='ikeproposal_bulk_delete'),
    path('ike-proposals/<int:pk>/', include(get_model_urls('vpn', 'ikeproposal'))),

    # IKE policies
    path('ike-policies/', views.IKEPolicyListView.as_view(), name='ikepolicy_list'),
    path('ike-policies/add/', views.IKEPolicyEditView.as_view(), name='ikepolicy_add'),
    path('ike-policies/import/', views.IKEPolicyBulkImportView.as_view(), name='ikepolicy_import'),
    path('ike-policies/edit/', views.IKEPolicyBulkEditView.as_view(), name='ikepolicy_bulk_edit'),
    path('ike-policies/delete/', views.IKEPolicyBulkDeleteView.as_view(), name='ikepolicy_bulk_delete'),
    path('ike-policies/<int:pk>/', include(get_model_urls('vpn', 'ikepolicy'))),

    # IPSec proposals
    path('ipsec-proposals/', views.IPSecProposalListView.as_view(), name='ipsecproposal_list'),
    path('ipsec-proposals/add/', views.IPSecProposalEditView.as_view(), name='ipsecproposal_add'),
    path('ipsec-proposals/import/', views.IPSecProposalBulkImportView.as_view(), name='ipsecproposal_import'),
    path('ipsec-proposals/edit/', views.IPSecProposalBulkEditView.as_view(), name='ipsecproposal_bulk_edit'),
    path('ipsec-proposals/delete/', views.IPSecProposalBulkDeleteView.as_view(), name='ipsecproposal_bulk_delete'),
    path('ipsec-proposals/<int:pk>/', include(get_model_urls('vpn', 'ipsecproposal'))),

    # IPSec policies
    path('ipsec-policies/', views.IPSecPolicyListView.as_view(), name='ipsecpolicy_list'),
    path('ipsec-policies/add/', views.IPSecPolicyEditView.as_view(), name='ipsecpolicy_add'),
    path('ipsec-policies/import/', views.IPSecPolicyBulkImportView.as_view(), name='ipsecpolicy_import'),
    path('ipsec-policies/edit/', views.IPSecPolicyBulkEditView.as_view(), name='ipsecpolicy_bulk_edit'),
    path('ipsec-policies/delete/', views.IPSecPolicyBulkDeleteView.as_view(), name='ipsecpolicy_bulk_delete'),
    path('ipsec-policies/<int:pk>/', include(get_model_urls('vpn', 'ipsecpolicy'))),

    # IPSec profiles
    path('ipsec-profiles/', views.IPSecProfileListView.as_view(), name='ipsecprofile_list'),
    path('ipsec-profiles/add/', views.IPSecProfileEditView.as_view(), name='ipsecprofile_add'),
    path('ipsec-profiles/import/', views.IPSecProfileBulkImportView.as_view(), name='ipsecprofile_import'),
    path('ipsec-profiles/edit/', views.IPSecProfileBulkEditView.as_view(), name='ipsecprofile_bulk_edit'),
    path('ipsec-profiles/delete/', views.IPSecProfileBulkDeleteView.as_view(), name='ipsecprofile_bulk_delete'),
    path('ipsec-profiles/<int:pk>/', include(get_model_urls('vpn', 'ipsecprofile'))),

    # L2VPN
    path('l2vpns/', views.L2VPNListView.as_view(), name='l2vpn_list'),
    path('l2vpns/add/', views.L2VPNEditView.as_view(), name='l2vpn_add'),
    path('l2vpns/import/', views.L2VPNBulkImportView.as_view(), name='l2vpn_import'),
    path('l2vpns/edit/', views.L2VPNBulkEditView.as_view(), name='l2vpn_bulk_edit'),
    path('l2vpns/delete/', views.L2VPNBulkDeleteView.as_view(), name='l2vpn_bulk_delete'),
    path('l2vpns/<int:pk>/', include(get_model_urls('vpn', 'l2vpn'))),

    # L2VPN terminations
    path('l2vpn-terminations/', views.L2VPNTerminationListView.as_view(), name='l2vpntermination_list'),
    path('l2vpn-terminations/add/', views.L2VPNTerminationEditView.as_view(), name='l2vpntermination_add'),
    path('l2vpn-terminations/import/', views.L2VPNTerminationBulkImportView.as_view(), name='l2vpntermination_import'),
    path('l2vpn-terminations/edit/', views.L2VPNTerminationBulkEditView.as_view(), name='l2vpntermination_bulk_edit'),
    path('l2vpn-terminations/delete/', views.L2VPNTerminationBulkDeleteView.as_view(), name='l2vpntermination_bulk_delete'),
    path('l2vpn-terminations/<int:pk>/', include(get_model_urls('vpn', 'l2vpntermination'))),

]

netbox/core/models/config.py
from django.core.cache import cache
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext, gettext_lazy as _

from utilities.querysets import RestrictedQuerySet

__all__ = (
    'ConfigRevision',
)


class ConfigRevision(models.Model):
    """
    An atomic revision of NetBox's configuration.
    """
    created = models.DateTimeField(
        verbose_name=_('created'),
        auto_now_add=True
    )
    comment = models.CharField(
        verbose_name=_('comment'),
        max_length=200,
        blank=True
    )
    data = models.JSONField(
        blank=True,
        null=True,
        verbose_name=_('configuration data')
    )

    objects = RestrictedQuerySet.as_manager()

    class Meta:
        ordering = ['-created']
        verbose_name = _('config revision')
        verbose_name_plural = _('config revisions')

    def __str__(self):
        if not self.pk:
            return gettext('Default configuration')
        if self.is_active:
            return gettext('Current configuration')
        return gettext('Config revision #{id}').format(id=self.pk)

    def __getattr__(self, item):
        if self.data and item in self.data:
            return self.data[item]
        return super().__getattribute__(item)

    def get_absolute_url(self):
        if not self.pk:
            return reverse('core:config')  # Default config view
        return reverse('core:configrevision', args=[self.pk])

    def activate(self):
        """
        Cache the configuration data.
        """
        cache.set('config', self.data, None)
        cache.set('config_version', self.pk, None)
    activate.alters_data = True

    @property
    def is_active(self):
        return cache.get('config_version') == self.pk

netbox/core/forms/bulk_edit.py
from django import forms
from django.utils.translation import gettext_lazy as _

from core.models import *
from netbox.forms import NetBoxModelBulkEditForm
from netbox.utils import get_data_backend_choices
from utilities.forms.fields import CommentField
from utilities.forms.widgets import BulkEditNullBooleanSelect

__all__ = (
    'DataSourceBulkEditForm',
)


class DataSourceBulkEditForm(NetBoxModelBulkEditForm):
    type = forms.ChoiceField(
        label=_('Type'),
        choices=get_data_backend_choices,
        required=False
    )
    enabled = forms.NullBooleanField(
        required=False,
        widget=BulkEditNullBooleanSelect(),
        label=_('Enabled')
    )
    description = forms.CharField(
        label=_('Description'),
        max_length=200,
        required=False
    )
    comments = CommentField()
    parameters = forms.JSONField(
        label=_('Parameters'),
        required=False
    )
    ignore_rules = forms.CharField(
        label=_('Ignore rules'),
        required=False,
        widget=forms.Textarea()
    )

    model = DataSource
    fieldsets = (
        (None, ('type', 'enabled', 'description', 'comments', 'parameters', 'ignore_rules')),
    )
    nullable_fields = (
        'description', 'description', 'parameters', 'comments', 'parameters', 'ignore_rules',
    )

netbox/core/forms/bulk_import.py
from core.models import *
from netbox.forms import NetBoxModelImportForm

__all__ = (
    'DataSourceImportForm',
)


class DataSourceImportForm(NetBoxModelImportForm):

    class Meta:
        model = DataSource
        fields = (
            'name', 'type', 'source_url', 'enabled', 'description', 'comments', 'parameters', 'ignore_rules',
        )

netbox/core/api/views.py
from django.shortcuts import get_object_or_404

from rest_framework.decorators import action
from rest_framework.exceptions import PermissionDenied
from rest_framework.response import Response
from rest_framework.routers import APIRootView
from rest_framework.viewsets import ReadOnlyModelViewSet

from core import filtersets
from core.models import *
from netbox.api.viewsets import NetBoxModelViewSet, NetBoxReadOnlyModelViewSet
from utilities.utils import count_related
from . import serializers


class CoreRootView(APIRootView):
    """
    Core API root view
    """
    def get_view_name(self):
        return 'Core'


class DataSourceViewSet(NetBoxModelViewSet):
    queryset = DataSource.objects.annotate(
        file_count=count_related(DataFile, 'source')
    )
    serializer_class = serializers.DataSourceSerializer
    filterset_class = filtersets.DataSourceFilterSet

    @action(detail=True, methods=['post'])
    def sync(self, request, pk):
        """
        Enqueue a job to synchronize the DataSource.
        """
        if not request.user.has_perm('core.sync_datasource'):
            raise PermissionDenied("Syncing data sources requires the core.sync_datasource permission.")

        datasource = get_object_or_404(DataSource, pk=pk)
        datasource.enqueue_sync_job(request)
        serializer = serializers.DataSourceSerializer(datasource, context={'request': request})

        return Response(serializer.data)


class DataFileViewSet(NetBoxReadOnlyModelViewSet):
    queryset = DataFile.objects.defer('data').prefetch_related('source')
    serializer_class = serializers.DataFileSerializer
    filterset_class = filtersets.DataFileFilterSet


class JobViewSet(ReadOnlyModelViewSet):
    """
    Retrieve a list of job results
    """
    queryset = Job.objects.prefetch_related('user')
    serializer_class = serializers.JobSerializer
    filterset_class = filtersets.JobFilterSet

netbox/templates/core/configrevision.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load perms %}
{% load plugins %}
{% load static %}
{% load i18n %}

{% block breadcrumbs %}
{% endblock %}

{% block controls %}
  <div class="controls">
    <div class="control-group">
      {% plugin_buttons object %}
      {% if not object.pk or object.is_active and perms.core.add_configrevision %}
        {% url 'core:configrevision_add' as edit_url %}
        {% include "buttons/edit.html" with url=edit_url %}
      {% endif %}
      {% if object.pk and not object.is_active and perms.core.delete_configrevision %}
        {% delete_button object %}
      {% endif %}
    </div>
    <div class="control-group">
      {% custom_links object %}
    </div>
  </div>
{% endblock controls %}

{% block subtitle %}
  {% if object.created %}
    <div class="object-subtitle">
      <span>{% trans "Created" %} {{ object.created|annotated_date }}</span>
    </div>
  {% endif %}
{% endblock subtitle %}

{% block content %}
  <div class="row">
    <div class="col col-md-12">
      <div class="card">
        <h5 class="card-header">{% trans "Rack Elevations" %}</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">{% trans "Default unit height" %}</th>
              <td>{{ object.data.RACK_ELEVATION_DEFAULT_UNIT_HEIGHT }}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "Default unit width" %}</th>
              <td>{{ object.data.RACK_ELEVATION_DEFAULT_UNIT_WIDTH }}</td>
            </tr>
          </table>
        </div>
      </div>

      <div class="card">
        <h5 class="card-header">{% trans "Power Feeds" %}</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">{% trans "Default voltage" %}</th>
              <td>{{ object.data.POWERFEED_DEFAULT_VOLTAGE }}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "Default amperage" %}</th>
              <td>{{ object.data.POWERFEED_DEFAULT_AMPERAGE }}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "Default max utilization" %}</th>
              <td>{{ object.data.POWERFEED_DEFAULT_MAX_UTILIZATION }}</td>
            </tr>
          </table>
        </div>
      </div>

      <div class="card">
        <h5 class="card-header">{% trans "IPAM" %}</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">{% trans "Enforce global unique" %}</th>
              <td>{{ object.data.ENFORCE_GLOBAL_UNIQUE }}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "Prefer IPv4" %}</th>
              <td>{{ object.data.PREFER_IPV4 }}</td>
            </tr>
          </table>
        </div>
      </div>

      <div class="card">
        <h5 class="card-header">{% trans "Security" %}</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">{% trans "Allowed URL schemes" %}</th>
              <td>{{ object.data.ALLOWED_URL_SCHEMES|join:", "|placeholder }}</td>
            </tr>
          </table>
        </div>
      </div>

      <div class="card">
        <h5 class="card-header">{% trans "Banners" %}</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">{% trans "Login banner" %}</th>
              <td>{{ object.data.BANNER_LOGIN }}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "Maintenance banner" %}</th>
              <td>{{ object.data.BANNER_MAINTENANCE }}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "Top banner" %}</th>
              <td>{{ object.data.BANNER_TOP }}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "Bottom banner" %}</th>
              <td>{{ object.data.BANNER_BOTTOM }}</td>
            </tr>
          </table>
        </div>
      </div>

      <div class="card">
        <h5 class="card-header">{% trans "Pagination" %}</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">{% trans "Paginate count" %}</th>
              <td>{{ object.data.PAGINATE_COUNT }}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "Max page size" %}</th>
              <td>{{ object.data.MAX_PAGE_SIZE }}</td>
            </tr>
          </table>
        </div>
      </div>

      <div class="card">
        <h5 class="card-header">{% trans "Validation" %}</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">{% trans "Custom validators" %}</th>
              {% if object.data.CUSTOM_VALIDATORS %}
                <td class="font-monospace">
                  <pre>{{ object.data.CUSTOM_VALIDATORS|json }}</pre>
                </td>
              {% else %}
                <td>{{ ''|placeholder }}</td>
              {% endif %}
            </tr>
            <tr>
              <th scope="row">{% trans "Protection rules" %}</th>
              {% if object.data.PROTECTION_RULES %}
                <td>
                  <pre>{{ object.data.PROTECTION_RULES|json }}</pre>
                </td>
              {% else %}
                <td>{{ ''|placeholder }}</td>
              {% endif %}
            </tr>
          </table>
        </div>
      </div>

      <div class="card">
        <h5 class="card-header">{% trans "User Preferences" %}</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">{% trans "Default user preferences" %}</th>
              {% if object.data.DEFAULT_USER_PREFERENCES %}
                <td>
                  <pre>{{ object.data.DEFAULT_USER_PREFERENCES|json }}</pre>
                </td>
              {% else %}
                <td>{{ ''|placeholder }}</td>
              {% endif %}
            </tr>
          </table>
        </div>
      </div>

      <div class="card">
        <h5 class="card-header">{% trans "Miscellaneous" %}</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">{% trans "Maintenance mode" %}</th>
              <td>{{ object.data.MAINTENANCE_MODE }}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "GraphQL enabled" %}</th>
              <td>{{ object.data.GRAPHQL_ENABLED }}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "Changelog retention" %}</th>
              <td>{{ object.data.CHANGELOG_RETENTION }}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "Job retention" %}</th>
              <td>{{ object.data.JOB_RETENTION }}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "Maps URL" %}</th>
              <td>{{ object.data.MAPS_URL }}</td>
            </tr>
          </table>
        </div>
      </div>

      <div class="card">
        <h5 class="card-header">{% trans "Comment" %}</h5>
        <div class="card-body">
          {{ object.comment|placeholder }}
        </div>
      </div>

    </div>
  </div>
{% endblock %}

netbox/templates/core/datafile.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load perms %}
{% load plugins %}
{% load i18n %}

{% block breadcrumbs %}
  {{ block.super }}
  <li class="breadcrumb-item"><a href="{% url 'core:datafile_list' %}?source_id={{ object.source.pk }}">{{ object.source }}</a></li>
{% endblock %}

{% block controls %}
  <div class="controls">
    <div class="control-group">
      {% plugin_buttons object %}
    </div>
    {% if request.user|can_delete:object %}
      {% delete_button object %}
    {% endif %}
    <div class="control-group">
      {% custom_links object %}
    </div>
  </div>
{% endblock controls %}

{% block content %}
  <div class="row mb-3">
    <div class="col">
      <div class="card">
        <h5 class="card-header">{% trans "Data File" %}</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">{% trans "Source" %}</th>
              <td>{{ object.source|linkify }}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "Path" %}</th>
              <td>
                <span class="font-monospace" id="datafile_path">{{ object.path }}</span>
                {% copy_content "datafile_path" %}
              </td>
            </tr>
            <tr>
              <th scope="row">{% trans "Last Updated" %}</th>
              <td>{{ object.last_updated }}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "Size" %}</th>
              <td>{{ object.size }} {% trans "bytes" %}</td>
            </tr>
            <tr>
              <th scope="row">{% trans "SHA256 Hash" %}</th>
              <td>
              <span class="font-monospace" id="datafile_hash">{{ object.hash }}</span>
                {% copy_content "datafile_hash" %}
              </td>
            </tr>
          </table>
        </div>
      </div>
      <div class="card">
        <h5 class="card-header">{% trans "Content" %}</h5>
        <div class="card-body">
          <pre>{{ object.data_as_string }}</pre>
        </div>
      </div>
      {% plugin_left_page object %}
    </div>
  </div>
  <div class="row mb-3">
    <div class="col col-md-12">
      {% plugin_full_width_page object %}
    </div>
  </div>
{% endblock %}